import os
import pickle
import shutil
import cv2
import numpy as np
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import (QThread, pyqtSignal)
from PyQt5.QtGui import QPixmap
from pynput.keyboard import Key, Controller

from cv_code import Gesture_detector
from prompt import PromptWindow

detector_obj = Gesture_detector() 


class Thread(QThread):
    #custom thread class that is used to update the camera frames in the gui
    changeframe = pyqtSignal(np.ndarray)

    def run(self):
        while True:
            ret, frame = detector_obj.frame_with_ROI() # get the current camera frame + Region of interest
            if ret:
                self.changeframe.emit(frame) # emit signal to send the frame to the view_image function


class Control_Panel(QtWidgets.QWidget):

    def setupUi(self, Form): #setuping window attributes (auto generated using qt designer and edited)

        self.profiles = self.load_profiles()
        Form.setObjectName("Form")
        Form.resize(810, 640)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1.5)
        sizePolicy.setVerticalStretch(2)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Hand-of-the-king-pin.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setStyleSheet("QWidget {\n"
                           "   background-color: #383c41;\n"
                           "}\n"
                           "\n"
                           "QTextEdit {\n"
                           "   background-color: aliceblue;\n"
                           "   color: #000000;\n"
                           "   font-weight: bold;\n"
                           "   font-size: 7pt;\n"
                           "}\n"
                           "\n"
                           "QLabel {\n"
                           "   background-color: #383c41;\n"
                           "   color: #FFA500;\n"
                           "}\n"
                           "\n"
                           "QPushButton {\n"
                           "   background-color: #FFA500;\n"
                           "   color: #ffffff;\n"
                           "   border-radius: 5px;\n"
                           "   border-style: none;\n"
                           "   height: 25px;\n"
                           "}\n"
                           "QPushButton::pressed {background-color:#F0E68C;color: #000000}\n"
                           "QPushButton::hover::!pressed {background-color: #00ab66}\n"
                           "QGroupBox {\n"
                           "    color:#ffffff;\n"
                           "}\n"
                           "QComboBox{\n"
                           "   color: #FFA500;\n"
                           "}\n"
                           "\n"
                           "QTabBar::tab{\n"
                           "    color:#ffffff;\n"
                           "}")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(-2, -2, 811, 641))
        self.tabWidget.setFocusPolicy(QtCore.Qt.TabFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.tabWidget.setObjectName("tabWidget")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.textEdit_73 = QtWidgets.QTextEdit(self.widget)
        self.textEdit_73.setGeometry(QtCore.QRect(0, -20, 811, 641))
        self.textEdit_73.setStyleSheet("QTextEdit{\n"
                                       "    background-color: #383c41;\n"
                                       "    color:#ffffff;\n"
                                       "}\n"
                                       "\n"
                                       "")
        self.textEdit_73.setFrameShadow(QtWidgets.QFrame.Raised)
        self.textEdit_73.setObjectName("textEdit_73")
        self.frame = QtWidgets.QFrame(self.widget)
        self.frame.setGeometry(QtCore.QRect(580, 60, 31, 61))
        self.frame.setStyleSheet("QFrame{\n"
                                 "    background: url(/home/tity/Hand-of-the-king-pin.png)\n"
                                 "}")
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.tabWidget.addTab(self.widget, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.label_25 = QtWidgets.QLabel(self.tab)
        self.label_25.setGeometry(QtCore.QRect(20, 20, 351, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.ComboBox_profiles = QtWidgets.QComboBox(self.tab)
        self.ComboBox_profiles.setGeometry(QtCore.QRect(410, 20, 181, 31))
        self.ComboBox_profiles.setObjectName("ComboBox_profiles")
        self.groupBox = QtWidgets.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(30, 70, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 190, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 80, 48, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.textEdit_1_left = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_1_left.setGeometry(QtCore.QRect(80, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_1_left.setFont(font)
        self.textEdit_1_left.setObjectName("textEdit_1_left")
        self.textEdit_1_right = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_1_right.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_1_right.setFont(font)
        self.textEdit_1_right.setObjectName("textEdit_1_right")
        self.textEdit_1_down = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_1_down.setGeometry(QtCore.QRect(80, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)
        font.setWeight(75)
        self.textEdit_1_down.setFont(font)
        self.textEdit_1_down.setObjectName("textEdit_1_down")
        self.textEdit_1_up = QtWidgets.QTextEdit(self.groupBox)
        self.textEdit_1_up.setGeometry(QtCore.QRect(80, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_1_up.setFont(font)
        self.textEdit_1_up.setObjectName("textEdit_1_up")
        self.groupBox_4 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(250, 70, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_4.setFont(font)
        self.groupBox_4.setObjectName("groupBox_4")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(10, 40, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 190, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(10, 140, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 80, 48, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.textEdit_2_left = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2_left.setGeometry(QtCore.QRect(80, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_2_left.setFont(font)
        self.textEdit_2_left.setObjectName("textEdit_2_left")
        self.textEdit_2_right = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2_right.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_2_right.setFont(font)
        self.textEdit_2_right.setObjectName("textEdit_2_right")
        self.textEdit_2_down = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2_down.setGeometry(QtCore.QRect(80, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_2_down.setFont(font)
        self.textEdit_2_down.setObjectName("textEdit_2_down")
        self.textEdit_2_up = QtWidgets.QTextEdit(self.groupBox_4)
        self.textEdit_2_up.setGeometry(QtCore.QRect(80, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_2_up.setFont(font)
        self.textEdit_2_up.setObjectName("textEdit_2_up")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(470, 70, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 40, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.groupBox_3)
        self.label_10.setGeometry(QtCore.QRect(10, 190, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.groupBox_3)
        self.label_11.setGeometry(QtCore.QRect(10, 140, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_3)
        self.label_12.setGeometry(QtCore.QRect(10, 80, 48, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.textEdit_3_left = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3_left.setGeometry(QtCore.QRect(80, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_3_left.setFont(font)
        self.textEdit_3_left.setObjectName("textEdit_3_left")
        self.textEdit_3_right = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3_right.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_3_right.setFont(font)
        self.textEdit_3_right.setObjectName("textEdit_3_right")
        self.textEdit_3_down = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3_down.setGeometry(QtCore.QRect(80, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_3_down.setFont(font)
        self.textEdit_3_down.setObjectName("textEdit_3_down")
        self.textEdit_3_up = QtWidgets.QTextEdit(self.groupBox_3)
        self.textEdit_3_up.setGeometry(QtCore.QRect(80, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_3_up.setFont(font)
        self.textEdit_3_up.setObjectName("textEdit_3_up")
        self.groupBox_5 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(470, 330, 171, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_5.setFont(font)
        self.groupBox_5.setObjectName("groupBox_5")
        self.textEdit_0_left = QtWidgets.QTextEdit(self.groupBox_5)
        self.textEdit_0_left.setGeometry(QtCore.QRect(40, 60, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_0_left.setFont(font)
        self.textEdit_0_left.setObjectName("textEdit_0_left")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_6.setGeometry(QtCore.QRect(250, 330, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.label_21 = QtWidgets.QLabel(self.groupBox_6)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.groupBox_6)
        self.label_22.setGeometry(QtCore.QRect(10, 190, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.groupBox_6)
        self.label_23.setGeometry(QtCore.QRect(10, 140, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.groupBox_6)
        self.label_24.setGeometry(QtCore.QRect(10, 80, 48, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.textEdit_5_left = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5_left.setGeometry(QtCore.QRect(80, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_5_left.setFont(font)
        self.textEdit_5_left.setObjectName("textEdit_5_left")
        self.textEdit_5_right = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5_right.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_5_right.setFont(font)
        self.textEdit_5_right.setObjectName("textEdit_5_right")
        self.textEdit_5_down = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5_down.setGeometry(QtCore.QRect(80, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_5_down.setFont(font)
        self.textEdit_5_down.setObjectName("textEdit_5_down")
        self.textEdit_5_up = QtWidgets.QTextEdit(self.groupBox_6)
        self.textEdit_5_up.setGeometry(QtCore.QRect(80, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_5_up.setFont(font)
        self.textEdit_5_up.setObjectName("textEdit_5_up")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 330, 171, 241))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 40, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 48, 14))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(10, 140, 48, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(10, 80, 48, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.textEdit_4_left = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4_left.setGeometry(QtCore.QRect(80, 40, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_4_left.setFont(font)
        self.textEdit_4_left.setObjectName("textEdit_4_left")
        self.textEdit_4_right = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4_right.setGeometry(QtCore.QRect(80, 90, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_4_right.setFont(font)
        self.textEdit_4_right.setObjectName("textEdit_4_right")
        self.textEdit_4_down = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4_down.setGeometry(QtCore.QRect(80, 190, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_4_down.setFont(font)
        self.textEdit_4_down.setObjectName("textEdit_4_down")
        self.textEdit_4_up = QtWidgets.QTextEdit(self.groupBox_2)
        self.textEdit_4_up.setGeometry(QtCore.QRect(80, 140, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(6)
        font.setBold(True)

        font.setWeight(75)
        self.textEdit_4_up.setFont(font)
        self.textEdit_4_up.setObjectName("textEdit_4_up")
        self.Btn_Save = QtWidgets.QPushButton(self.tab)
        self.Btn_Save.setGeometry(QtCore.QRect(620, 590, 80, 21))
        self.Btn_Save.setObjectName("Btn_Save")
        self.Btn_Save.setToolTip('Click to save key bindings to a profile')

        self.Btn_default = QtWidgets.QPushButton(self.tab)
        self.Btn_default.setGeometry(QtCore.QRect(520, 590, 90, 21))
        self.Btn_default.setObjectName("Btn_default")
        self.Btn_default.setToolTip('click to restore the default profile (note: need to restart app)')
        self.Btn_default.clicked.connect(self.restore_defaults)

        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.frame_2 = QtWidgets.QLabel(self.tab_2)
        self.frame_2.setGeometry(QtCore.QRect(10, 20, 711, 511))
        self.frame_2.setObjectName("frame_2")
        self.frame_2.setAutoFillBackground(True)

        self.Btn_Go = QtWidgets.QPushButton(self.tab_2)
        self.Btn_Go.setGeometry(QtCore.QRect(610, 580, 81, 21))
        self.Btn_Go.setStyleSheet("QPushButton {\n"
                                  "   background-color: #00ab66;\n"
                                  "   color: #ffffff;\n"
                                  "   border-radius: 5px;\n"
                                  "   border-style: none;\n"
                                  "   height: 25px;\n"
                                  "}")
        self.Btn_Go.setObjectName("Btn_Go")
        self.Btn_Go.clicked.connect(self.go_on_click)

        self.Btn_Capture = QtWidgets.QPushButton(self.tab_2)
        self.Btn_Capture.setGeometry(QtCore.QRect(230, 580, 81, 21))
        self.Btn_Capture.setObjectName("Btn_Capture")
        self.Btn_Capture.setToolTip('Click to capture background')
        self.Btn_Capture.clicked.connect(self.capture_on_click)

        self.label_69 = QtWidgets.QLabel(self.tab_2)
        self.label_69.setGeometry(QtCore.QRect(10, 550, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_69.setFont(font)
        self.label_69.setObjectName("label_69")
        self.Slider_Senitivity = QtWidgets.QSlider(self.tab_2)
        self.Slider_Senitivity.setGeometry(QtCore.QRect(40, 580, 160, 31))
        self.Slider_Senitivity.setMaximum(100)
        self.Slider_Senitivity.setProperty("value", 40)
        self.Slider_Senitivity.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Senitivity.setObjectName("Slider_Senitivity")
        self.tabWidget.addTab(self.tab_2, "")
        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)

        QtCore.QMetaObject.connectSlotsByName(Form)
